### ISSUE TITLE
Processing vignettes fails when there are child documents to include, maybe?

### ISSUE THREAD

**Issue by bryanhanson** [etiennebacher/altdoc#279]
Decided to try out `altdoc`.  I'm working on the package [here](https://github.com/bryanhanson/LearnPCA); main branch is fine for testing.  I set up the environment using `docsify`.

I tried to render and got an error:

```
R > render_docs()
✔ Converting vignette 11/11: works_consulted.md [5ms][939ms]s]ms]s]

✖ 3The conversion failed for the following vignettes:
  • 'Vig_01_Start_Here.Rmd'
  • 'Vig_02_Conceptual_Intro_PCA.Rmd'
  • 'Vig_03_Step_By_Step_PCA.Rmd'
  • 'Vig_04_Scores_Loadings.Rmd'
  • 'Vig_05_Visualizing_PCA_3D.Rmd'
  • 'Vig_06_Math_Behind_PCA.Rmd'
  • 'Vig_07_Functions_PCA.Rmd'
  • 'Vig_08_Notes.Rmd'

Error in `render_docs()`:
! There were some failures when rendering vignettes and man pages.
Run `rlang::last_trace()` to see where the error occurred.
```

Runinng `last_trace` was not informative.  These vignettes have three supporting files: `works_consulted.md` and `top_matter.md` and `refer_to_works_consulted.md`  These supporting files are included in the numbered vignettes via a `knit_child` approach.  None of them should be presented as vignettes by themselves.

Not sure what the exact problem is here, so I thought you should know about it.  Perhaps there needs to be an "ignore" or "skip" argument somewhere so these supporting files are not processed, but will be found for inclusion purposes.  Or maybe the problem is something entirely different...

I don't see any open or closed issue along these lines; hopefully I didn't miss one that applies.  Thanks.

**Comment by vincentarelbundock** [comment]
Can you run it again with `verbose=TRUE` to see if you get a more informative error message?

**Comment by bryanhanson** [comment]
Sure... More loquacious than verbose!  Tons of complaints.  I do have a development version of `quarto` installed if that's relevant.

```
R > render_docs(verbose = TRUE)
[31mError in rmarkdown:::abs_path(input) : atpackage [1.6s]
  The file 'docs/man/PCAtoXhat.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[1mpandoc [22mction reference 3/4: PCsearcht [1.6s]
  to: >-
    markdown_strict+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links
  output-file: PCsearch.md
  standalone: true
  default-image-extension: png
  
Output created: PCsearch.md

[31mError in rmarkdown:::abs_path(input) : oXhat8s]
  The file 'docs/man/XtoPCAtoXhat.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[31mError in rmarkdown:::abs_path(input) : e.Rmdted.md [5ms]
  The file 'docs/vignettes/Vig_01_Start_Here.Rmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[91mERROR: Validation of YAML front matter failed.[39mRmd
ERROR: (line 21, columns 17--20) Field "[34mlink-citations[39m" has value [34myes[39m, which must instead be `true` or `false`

[31m✖[39m The value [34myes[39m is a string.
[34mℹ[39m The error happened in location [34mlink-citations[39m.
[34mℹ[39m Quarto uses YAML 1.2, which interprets booleans strictly.
[34mℹ[39m Try using [34mtrue[39m instead.

[91mERROR: Render failed due to invalid YAML.

Stack trace:
    at renderFileInternal (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:581:19)
    at async renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:325:9)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[31mError in rmarkdown:::abs_path(input) : tep_PCA.Rmd.Rmd [518ms]
  The file 'docs/vignettes/Vig_03_Step_By_Step_PCA.Rmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[31mError in rmarkdown:::abs_path(input) : adings.Rmdd [945ms]
  The file 'docs/vignettes/Vig_04_Scores_Loadings.Rmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[31mError in rmarkdown:::abs_path(input) : ng_PCA_3D.Rmd26ms]
  The file 'docs/vignettes/Vig_05_Visualizing_PCA_3D.Rmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[91mERROR: Validation of YAML front matter failed.[39md [939ms]
ERROR: (line 22, columns 17--20) Field "[34mlink-citations[39m" has value [34myes[39m, which must instead be `true` or `false`

[31m✖[39m The value [34myes[39m is a string.
[34mℹ[39m The error happened in location [34mlink-citations[39m.
[34mℹ[39m Quarto uses YAML 1.2, which interprets booleans strictly.
[34mℹ[39m Try using [34mtrue[39m instead.

[91mERROR: Render failed due to invalid YAML.

Stack trace:
    at renderFileInternal (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:581:19)
    at async renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:325:9)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[31mError in rmarkdown:::abs_path(input) : _PCA.Rmdmd [515ms]
  The file 'docs/vignettes/Vig_07_Functions_PCA.Rmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
[31mError in rmarkdown:::abs_path(input) : dPCA.Rmd [943ms]
  The file 'docs/vignettes/Vig_08_Notes.Rmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
[39m[91mERROR: Error
    at renderFiles (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/quarto.ts:160:3[39m
Error in quarto::quarto_render(input = path.expand(tar_file), output_format = "md",  : 
  ✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
✔ Converting vignette 11/11: works_consulted.md [5ms]

✖ 3The conversion failed for the following vignettes:
  • 'Vig_01_Start_Here.Rmd'
  • 'Vig_02_Conceptual_Intro_PCA.Rmd'
  • 'Vig_03_Step_By_Step_PCA.Rmd'
  • 'Vig_04_Scores_Loadings.Rmd'
  • 'Vig_05_Visualizing_PCA_3D.Rmd'
  • 'Vig_06_Math_Behind_PCA.Rmd'
  • 'Vig_07_Functions_PCA.Rmd'
  • 'Vig_08_Notes.Rmd'

Error in `render_docs()`:
! There were some failures when rendering vignettes and man pages.
Run `rlang::last_trace()` to see where the error occurred.
R > rlang::last_trace()
<error/rlang_error>
Error in `render_docs()`:
! There were some failures when rendering vignettes and man pages.
---
Backtrace:
    ▆
 1. └─altdoc::render_docs(verbose = TRUE)
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.
R > rlang::last_trace(drop = FALSE)
<error/rlang_error>
Error in `render_docs()`:
! There were some failures when rendering vignettes and man pages.
---
Backtrace:
    ▆
 1. └─altdoc::render_docs(verbose = TRUE)
 2.   └─cli::cli_abort("There were some failures when rendering vignettes and man pages.")
 3.     └─rlang::abort(...)
R > 
```

**Comment by etiennebacher** [comment]
Did you try with the github version of `altdoc`? https://github.com/etiennebacher/altdoc/pull/272 should have solved this unhelpful message "There were some failures..." even when `verbose = FALSE`

**Comment by vincentarelbundock** [comment]
I tried it with dev and it also broke. I'll look into this eventually but am booked at work right now.

**Comment by bryanhanson** [comment]
Thanks y'all.  I'm not in a hurry, and it looks like a slog to decipher.

**Comment by vincentarelbundock** [comment]
Not solved yet, but this seems Docsify-specific. I was able to build the website with `quarto_website` with minimal (mostly documented) changes: https://github.com/bryanhanson/LearnPCA/pull/15

Will try again with docsify when I find time.

**Comment by bryanhanson** [comment]
Thanks.  So I merged your commit over on `LearnPCA`, tried `render_docs()`. Then pulled it down locally for play.

First, I needed to remove a copy of `docsify.md` (I think that was it, complaint was "multiple formats").  Then re-ran `render_docs()` and it gave the following:

```
R > render_docs()

── Basic files ─────────────────────────────────────────────────────────────────────────────
✔ 'NEWS' imported.
✔ 'CODE_OF_CONDUCT' imported.
✔ Converting function reference 4/4: XtoPCAtoXhat [492ms]ms]

── Vignettes ───────────────────────────────────────────────────────────────────────────────

── Update HTML ─────────────────────────────────────────────────────────────────────────────
Error in finalize(settings, path, verbose, freeze) : 
  object 'src' not found
R > traceback()
9: which(is.na(x))
8: assert_no_missing(path)
7: fs::dir_ls(src)
6: which(is.na(x))
5: assert_no_missing(path)
4: fs::file_move(fs::dir_ls(src), tar)
3: finalize(settings, path, verbose, freeze)
2: .import_settings(path = path, tool = tool, verbose = verbose, 
       freeze = freeze)
1: render_docs()
```

Does this point to something simple, an error on my end?  Again, no hurry.

**Comment by vincentarelbundock** [comment]
oops, I think this is probably because I was using the development version of altdoc from GitHub:

```r
remotes::install_github('etiennebacher/altdoc')
```

Then restart R completely and try again

**Comment by bryanhanson** [comment]
Yes, that fixes things.  Thank you.  Will look over the result carefully later today.

**Comment by bryanhanson** [comment]
Alright, looked over the local files produced by `preview_docs()`, this is the quarto website version from your PR.  Overall, it looks pretty nice!  There's some stuff there that results from the vignette files not being formatted for `quarto` properly, like figure cross-references.  No big deal, easily fixed if one wants to make the shift and go with this format.  Bonus: found a few typos since I was looking with fresh eyes.

*This should probably be in a new issue but will let you all decide how to proceed* The one thing that seems that it might come from the particulars of `altdoc` processing is that the footnotes to the authors' names are repeated 3x.  There are 2 authors, and 6 footnotes as a result.  These footnotes are created in the yaml entries at the top of the document, and this occurs in every document (not a surprise, the same yaml is present in each).  However, maybe this too is an artifact of not formatting things in a quarto-specific manner.

**Comment by vincentarelbundock** [comment]
Circling back to this. It looks like you may have uncovered a Quarto bug.

Would you mind create a document with a `.qmd` extension and the following content:

````
---
title:  "A Conceptual Introduction to PCA"
author:
  - David T. Harvey^[Professor of Chemistry & Biochemistry, DePauw University, Greencastle IN USA., harvey@depauw.edu]
  - Bryan A. Hanson^[Professor Emeritus of Chemistry & Biochemistry, DePauw University, Greencastle IN USA., hanson@depauw.edu]
---


blah blah blah
````

Then, use Quarto to compile it to HTML. On my computer I get duplicated footnotes.

**Comment by bryanhanson** [comment]
Yes, I can confirm that happens.  Here's what I see.  I processed this using the dev version of Quarto downloaded and installed a few minutes ago.  Do you want me to report over there? I'm going to go search their issues.

<img width="788" alt="Screenshot 2024-05-16 at 7 52 31 AM" src="https://github.com/etiennebacher/altdoc/assets/140350/61a5bf5b-5d3d-473b-a63c-ef6f789fc5ff">

**Comment by vincentarelbundock** [comment]
Ah good. That's a relief. Yes, I think it'd be a good idea to report a minimal example there if they don't have an existing issue.

**Comment by bryanhanson** [comment]
Did not see any issues on this topic for `quarto-cli`.  Someone observed the same thing [here](https://stackoverflow.com/questions/77198089/how-to-add-footnote-in-the-yaml-block-of-a-quarto-document).  I will report later today.

I think my original issue is fixed, but I'll let you decide on closing.  Thanks for your help!

**Comment by vincentarelbundock** [comment]
Sounds great, thanks!

And thanks for opening the issue in the first place. Your website was a fun one to play with because it uses a bunch of features I had not tried.
